version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/deploy_frontend
hooks:
  BeforeInstall:
    - location: scripts/install_frontend.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_frontend.sh
      timeout: 300
      runas: root
